# Generated by Django 3.2.4 on 2022-06-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('rut', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
            ],
        ),
    ]
