# Generated by Django 3.2.4 on 2022-06-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salida', '0001_initial'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='salidas',
            field=models.ManyToManyField(to='salida.Salida'),
        ),
    ]
