# Generated by Django 3.2.4 on 2022-06-05 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_persona_salidas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='salidas',
        ),
    ]
