# Generated by Django 3.2.4 on 2022-06-19 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_persona_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='names',
            new_name='nombres',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='first_name',
            new_name='primer_apellido',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='second_name',
            new_name='segundo_apellido',
        ),
    ]
