# Generated by Django 3.2.4 on 2022-06-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_persona_salidas'),
        ('salida', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salida',
            name='personas',
            field=models.ManyToManyField(to='persona.Persona'),
        ),
    ]
