# Generated by Django 3.2.4 on 2022-06-05 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salida', '0002_salida_personas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salida',
            name='personas',
        ),
    ]
