# Generated by Django 3.2.4 on 2022-06-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salida', '0003_remove_salida_personas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salida',
            name='hora',
        ),
        migrations.AddField(
            model_name='salida',
            name='foto_salida',
            field=models.ImageField(blank=True, upload_to='salida'),
        ),
    ]
