# Generated by Django 3.2.4 on 2022-06-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salida', '0004_auto_20220613_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salida',
            name='foto_salida',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
