# Generated by Django 3.2.4 on 2022-06-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0006_auto_20220619_0046'),
        ('salida', '0005_alter_salida_foto_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='salida',
            name='lista_personas',
            field=models.ManyToManyField(to='persona.Persona'),
        ),
    ]
